// Generated by scripts/build-running-feed.mjs. Do not edit directly.
// Compile time: 2026-09-29T01:38:46.082Z

export interface RunningFeedArticle {
  readonly sourceId: string;
  readonly sourceName: string;
  readonly category: string;
  readonly title: string;
  readonly link: string;
  readonly publishedAt: string;
  readonly snippet: string;
}

export const RUNNING_FEED_COMPILED_AT = "2026-09-29T01:38:46.082Z";

export const RUNNING_FEED_ARTICLES: readonly RunningFeedArticle[] = [
  {
    "sourceId": "aldaily",
    "sourceName": "Arts & Letters Daily",
    "category": "culture",
    "title": "Perverseness drove Edgar Allan Poe to ruin, or the brink of it, again and again. It was also the source of his inspiration",
    "link": "https://newrepublic.com/article/214970/edgar-allan-poe-mined-misery-emily-ogden",
    "publishedAt": "2026-09-29T01:38:37.824Z",
    "snippet": "Perverseness drove Edgar Allan Poe to ruin, or the brink of it, again and again. It was also the source of his inspiration"
  },
  {
    "sourceId": "aldaily",
    "sourceName": "Arts & Letters Daily",
    "category": "culture",
    "title": "The Egyptians, the Hittites, the Assyrians — what caused the collapse of a slew of regional powers around 1200 BC?",
    "link": "https://www.worksinprogress.news/p/why-really-caused-the-bronze-age",
    "publishedAt": "2026-09-29T01:38:37.824Z",
    "snippet": "The Egyptians, the Hittites, the Assyrians — what caused the collapse of a slew of regional powers around 1200 BC?"
  },
  {
    "sourceId": "aldaily",
    "sourceName": "Arts & Letters Daily",
    "category": "culture",
    "title": "AI doomers and apocalyptic futurists are weird. Also, their prophecies risk pernicious downsides. That doesn't mean they're wrong",
    "link": "https://quillette.substack.com/p/an-open-letter-to-scott-alexander",
    "publishedAt": "2026-09-29T01:38:37.824Z",
    "snippet": "AI doomers and apocalyptic futurists are weird. Also, their prophecies risk pernicious downsides. That doesn't mean they're wrong"
  },
  {
    "sourceId": "aldaily",
    "sourceName": "Arts & Letters Daily",
    "category": "culture",
    "title": "Egomaniacs, psychos, and informants. Why is it we look past all sorts of ugliness and insist on mythologizing revolutionaries?",
    "link": "https://theamericanscholar.org/the-allure-of-eden-on-earth/",
    "publishedAt": "2026-09-29T01:38:37.824Z",
    "snippet": "Egomaniacs, psychos, and informants. Why is it we look past all sorts of ugliness and insist on mythologizing revolutionaries?"
  },
  {
    "sourceId": "aldaily",
    "sourceName": "Arts & Letters Daily",
    "category": "culture",
    "title": "As an AI-generated sameness permeates “creative” work and the knowledge economy, we’re entering an era of bleh",
    "link": "https://www.noemamag.com/now-entering-the-era-of-bleh",
    "publishedAt": "2026-09-29T01:38:37.824Z",
    "snippet": "As an AI-generated sameness permeates “creative” work and the knowledge economy, we’re entering an era of bleh"
  },
  {
    "sourceId": "kottke",
    "sourceName": "Kottke.org",
    "category": "culture",
    "title": "type=\"html\">This American Life has a whole episode with Nikole...",
    "link": "https://kottke.org/26/09/0049687-this-american-life-has-a-",
    "publishedAt": "2026-09-29T01:25:00.000Z",
    "snippet": "type=\"html\" xml:lang=\"en-us\" xml:base=\"https://kottke.org/\"> This American Life has a whole episode with Nikole Hannah-Jones and her daughte"
  },
  {
    "sourceId": "kottke",
    "sourceName": "Kottke.org",
    "category": "culture",
    "title": "type=\"html\">Whoa, for the 50th anniversary of Songs in the Key of...",
    "link": "https://kottke.org/26/09/0049686-stevie-wonder-has-release",
    "publishedAt": "2026-09-29T00:45:00.000Z",
    "snippet": "type=\"html\" xml:lang=\"en-us\" xml:base=\"https://kottke.org/\"> Whoa, for the 50th anniversary of Songs in the Key of Life, Stevie Wonder has r"
  },
  {
    "sourceId": "simon-willison",
    "sourceName": "Simon Willison's Weblog",
    "category": "technology",
    "title": "Claude Sonnet 5.5",
    "link": "https://simonwillison.net/2026/Sep/28/claude-sonnet-5-5/",
    "publishedAt": "2026-09-28T22:07:38.000Z",
    "snippet": "type=\"html\"> <p><strong><a href=\"https://www.anthropic.com/claude-sonnet-5-5\">Claude Sonnet 5.5</a></strong></p> New Sonnet model from Anthr"
  },
  {
    "sourceId": "adafruit-blog-esp32",
    "sourceName": "Adafruit Blog (ESP32)",
    "category": "technology",
    "title": "Adding a non-WiFi Mitsubishi AC to Home Assistant",
    "link": "https://blog.adafruit.com/2026/09/28/adding-a-non-wifi-mitsubishi-ac-to-home-assistant/",
    "publishedAt": "2026-09-28T20:37:59.000Z",
    "snippet": "A Medium post walks through putting a ducted Mitsubishi air conditioner on Home Assistant without Mitsubishi’s own WiFi adapter. The unit, a"
  },
  {
    "sourceId": "adafruit-blog-esp32",
    "sourceName": "Adafruit Blog (ESP32)",
    "category": "technology",
    "title": "SquachWatch: firmware for the Cheap Yellow Display that gamifies detecting things",
    "link": "https://blog.adafruit.com/2026/09/28/squachwatch-firmware-for-the-cheap-yellow-display-that-gamifies-detecting-things/",
    "publishedAt": "2026-09-28T19:55:29.000Z",
    "snippet": "TalkingSasquach has published SquachWatch-CYD on GitHub, firmware that turns the ESP32-2432S028R “Cheap Yellow Display” into a surveillance "
  },
  {
    "sourceId": "nieman-lab",
    "sourceName": "Nieman Lab",
    "category": "news",
    "title": "A lack of professional AI guidelines leads to feelings of “AI shame,” a new study finds",
    "link": "https://www.niemanlab.org/2026/09/a-lack-of-professional-ai-guidelines-leads-to-feelings-of-ai-shame-a-new-study-finds/",
    "publishedAt": "2026-09-28T19:55:29.000Z",
    "snippet": "Are you a journalist who has used AI for work in some capacity but been nervous to tell anyone about it? Worried about how your bosses might"
  },
  {
    "sourceId": "simon-willison",
    "sourceName": "Simon Willison's Weblog",
    "category": "technology",
    "title": "Quoting @joedaroo",
    "link": "https://simonwillison.net/2026/Sep/28/joedaroo/",
    "publishedAt": "2026-09-28T19:11:42.000Z",
    "snippet": "type=\"html\"> <blockquote cite=\"https://twitter.com/joedaroo/status/2104335929293127851\"><p>To say that we were surprised at the jump and sud"
  },
  {
    "sourceId": "nieman-lab",
    "sourceName": "Nieman Lab",
    "category": "news",
    "title": "OpenAI doubles support for Lenfest’s AI and local news fellowships",
    "link": "https://www.niemanlab.org/2026/09/openai-doubles-support-for-lenfests-ai-and-local-news-fellowships/",
    "publishedAt": "2026-09-28T17:02:39.000Z",
    "snippet": "OpenAI announced on Monday that it’s doubling its support for the Lenfest Institute’s AI Collaborative and Fellowship Program. Since the pro"
  },
  {
    "sourceId": "propublica",
    "sourceName": "ProPublica",
    "category": "news",
    "title": "The Untold Origins of Trump’s Plan to Sharply Restrict Mail-In Voting",
    "link": "https://www.propublica.org/article/trumps-plan-to-restrict-mail-voting",
    "publishedAt": "2026-09-28T15:30:00.000Z",
    "snippet": "The post The Untold Origins of Trump’s Plan to Sharply Restrict Mail-In Voting appeared first on ProPublica ."
  },
  {
    "sourceId": "quanta-magazine",
    "sourceName": "Quanta Magazine",
    "category": "culture",
    "title": "Mathematicians Harness Randomness To Crack a 55-Year-Old Conjecture",
    "link": "https://www.quantamagazine.org/mathematicians-harness-randomness-to-crack-a-55-year-old-conjecture-20260928/",
    "publishedAt": "2026-09-28T14:35:21.000Z",
    "snippet": "After a long hiatus, the problem, which was likely inspired by juggling, has finally been resolved by a group of young mathematicians. The p"
  },
  {
    "sourceId": "rest-of-world",
    "sourceName": "Rest of World",
    "category": "technology",
    "title": "South Korea’s AI chip giants are fighting for a bigger role in America’s AI boom",
    "link": "https://restofworld.org/2026/samsung-sk-hynix-ai-memory-chip-war-nvidia-openai/?utm_source=rss&utm_medium=rss&utm_campaign=feeds",
    "publishedAt": "2026-09-28T10:00:00.000Z",
    "snippet": "Samsung and SK Hynix dominate the high-bandwidth memory market. Now they are competing to become indispensable to Nvidia, OpenAI, and other "
  },
  {
    "sourceId": "propublica",
    "sourceName": "ProPublica",
    "category": "news",
    "title": "Arizona Lawmaker Proposes More Federal Support for English Fluency Services",
    "link": "https://www.propublica.org/article/arizona-english-fluency-legislation-adelita-grijalva",
    "publishedAt": "2026-09-28T10:00:00.000Z",
    "snippet": "The post Arizona Lawmaker Proposes More Federal Support for English Fluency Services appeared first on ProPublica ."
  },
  {
    "sourceId": "hugging-face-blog",
    "sourceName": "Hugging Face Blog",
    "category": "technology",
    "title": "Holo4: powering generalist computer-use agents",
    "link": "https://huggingface.co/blog/Hcompany/holo4",
    "publishedAt": "2026-09-28T09:44:05.000Z",
    "snippet": ""
  },
  {
    "sourceId": "propublica",
    "sourceName": "ProPublica",
    "category": "news",
    "title": "Two Years After Hurricane Helene, People Are Still Allowed to Live in Harm’s Way",
    "link": "https://www.propublica.org/article/hurricane-helene-flood-prone-areas",
    "publishedAt": "2026-09-28T09:00:00.000Z",
    "snippet": "The post Two Years After Hurricane Helene, People Are Still Allowed to Live in Harm’s Way appeared first on ProPublica ."
  },
  {
    "sourceId": "hackaday-esp32",
    "sourceName": "Hackaday ESP32",
    "category": "technology",
    "title": "An IR Blaster Project, in a Nutshell",
    "link": "https://hackaday.com/2026/09/28/an-ir-blaster-project-in-a-nutshell/",
    "publishedAt": "2026-09-28T08:00:00.000Z",
    "snippet": "The speed that computers have gotten smaller is a bit mind-bending. Most of us now walk around with computers in our pockets that would have"
  },
  {
    "sourceId": "simon-willison",
    "sourceName": "Simon Willison's Weblog",
    "category": "technology",
    "title": "Quoting Muse AI Agent",
    "link": "https://simonwillison.net/2026/Sep/28/muse-ai-agent/",
    "publishedAt": "2026-09-28T04:01:30.000Z",
    "snippet": "type=\"html\"> <blockquote cite=\"https://www.threads.com/share/_oWfPufYJ/\"><p>Bad news on the MX Keys Mini pickup. Usman showed up at your bui"
  },
  {
    "sourceId": "simon-willison",
    "sourceName": "Simon Willison's Weblog",
    "category": "technology",
    "title": "2026 in LLMs (so far)",
    "link": "https://simonwillison.net/2026/Sep/27/2026-in-llms-so-far/",
    "publishedAt": "2026-09-27T23:54:15.000Z",
    "snippet": "type=\"html\"> <p>On Friday I gave the closing keynote at the <a href=\"https://www.wearedevelopers.com/world-congress-north-america\">WeAreDeve"
  },
  {
    "sourceId": "simon-willison",
    "sourceName": "Simon Willison's Weblog",
    "category": "technology",
    "title": "S3 Is the Future, S3 Is the Past",
    "link": "https://simonwillison.net/2026/Sep/27/hn-49871741/",
    "publishedAt": "2026-09-27T23:09:19.000Z",
    "snippet": "type=\"html\"> <p><a href=\"https://news.ycombinator.com/item?id=49851693#49871741\">My comment</a> on <a href=\"https://news.ycombinator.com/ite"
  },
  {
    "sourceId": "hackaday-esp32",
    "sourceName": "Hackaday ESP32",
    "category": "technology",
    "title": "Cheap Yellow Display Dreams of PDA",
    "link": "https://hackaday.com/2026/09/26/cheap-yellow-display-dreams-of-pda/",
    "publishedAt": "2026-09-26T23:00:00.000Z",
    "snippet": "Everybody loves the Cheap Yellow Display (CYD) ESP32 dev boards, so why not treat yours to a little PDA? That’s right: turn it into a Portab"
  },
  {
    "sourceId": "hackaday-esp32",
    "sourceName": "Hackaday ESP32",
    "category": "technology",
    "title": "A Pocket-Sized Digital Fish Tank",
    "link": "https://hackaday.com/2026/09/26/a-pocket-sized-digital-fish-tank/",
    "publishedAt": "2026-09-26T17:00:21.000Z",
    "snippet": "The problem with trying to make a fish tank fit in your pocket is that you’ll either end up with water everywhere or a bunch of dead fish. P"
  },
  {
    "sourceId": "the-marshall-project",
    "sourceName": "The Marshall Project",
    "category": "news",
    "title": "From Sweltering Cells to Frigid Tents: The Extreme Temperatures of Incarceration",
    "link": "https://www.themarshallproject.org/2026/09/26/texas-heat-california-cold-prison",
    "publishedAt": "2026-09-26T16:00:00.000Z",
    "snippet": "While Texas faces a 2029 deadline to install AC and California debates workplace exemptions, incarcerated people endure extreme heat and fre"
  },
  {
    "sourceId": "propublica",
    "sourceName": "ProPublica",
    "category": "news",
    "title": "I Deliberately Bet Like a Problem Gambler. DraftKings Made Me a VIP.",
    "link": "https://www.propublica.org/article/draftkings-sports-gambling-problem-vip-fanduel",
    "publishedAt": "2026-09-26T09:00:00.000Z",
    "snippet": "The post I Deliberately Bet Like a Problem Gambler. DraftKings Made Me a VIP. appeared first on ProPublica ."
  },
  {
    "sourceId": "propublica",
    "sourceName": "ProPublica",
    "category": "news",
    "title": "What Does Your Data Reveal About Sports Betting Apps? Help ProPublica Find Out.",
    "link": "https://projects.propublica.org/sports-betting-uploader",
    "publishedAt": "2026-09-26T08:55:00.000Z",
    "snippet": "The post What Does Your Data Reveal About Sports Betting Apps? Help ProPublica Find Out. appeared first on ProPublica ."
  },
  {
    "sourceId": "latent-space",
    "sourceName": "Latent Space",
    "category": "technology",
    "title": "OpenRouter: from Seed to Stripe — with OpenRouter’s Alex Atallah & AMP’s Anjney Midha",
    "link": "https://www.latent.space/p/openrouter",
    "publishedAt": "2026-09-25T23:14:41.000Z",
    "snippet": "In 2023 most people doubted that there could be more than 1 or 2 frontier model labs. Now there are dozens.... and Stripe just bought the be"
  },
  {
    "sourceId": "kottke",
    "sourceName": "Kottke.org",
    "category": "culture",
    "title": "type=\"html\">What do you you do when the book you’re reading is too...",
    "link": "https://kottke.org/26/09/0049685-chop-that-book-up-into-re",
    "publishedAt": "2026-09-25T21:29:00.000Z",
    "snippet": "type=\"html\" xml:lang=\"en-us\" xml:base=\"https://kottke.org/\"> What do you you do when the book you’re reading is too large to carry around? “"
  },
  {
    "sourceId": "kottke",
    "sourceName": "Kottke.org",
    "category": "culture",
    "title": "type=\"html\">Well. I’m not sure what to think about this. The teaser...",
    "link": "https://kottke.org/26/09/0049677-the-teaser-trailer-for-ma",
    "publishedAt": "2026-09-25T20:39:00.000Z",
    "snippet": "type=\"html\" xml:lang=\"en-us\" xml:base=\"https://kottke.org/\"> Well. I’m not sure what to think about this. The teaser trailer for Madden , st"
  },
  {
    "sourceId": "kottke",
    "sourceName": "Kottke.org",
    "category": "culture",
    "title": "type=\"html\">What if America Went Completely Dark? “We came up with...",
    "link": "https://kottke.org/26/09/0049670-what-if-america-went-comp",
    "publishedAt": "2026-09-25T19:39:00.000Z",
    "snippet": "type=\"html\" xml:lang=\"en-us\" xml:base=\"https://kottke.org/\"> What if America Went Completely Dark? “We came up with some very astounding num"
  },
  {
    "sourceId": "quanta-magazine",
    "sourceName": "Quanta Magazine",
    "category": "culture",
    "title": "Gravity Seems Holographic. What Does That Mean for Reality?",
    "link": "https://www.quantamagazine.org/gravity-seems-holographic-what-does-that-mean-for-reality-20260925/",
    "publishedAt": "2026-09-25T14:40:26.000Z",
    "snippet": "The biggest breakthrough in modern theoretical physics is the discovery that gravity can collapse the dimensions of space. Physicists don’t "
  },
  {
    "sourceId": "nieman-lab",
    "sourceName": "Nieman Lab",
    "category": "news",
    "title": "The Boston Globe’s Western Mass lesbian bar story pulled in “several thousand” new subscribers in about 72 hours",
    "link": "https://www.niemanlab.org/2026/09/the-boston-globes-western-mass-lesbian-bar-story-pulled-in-several-thousand-new-subscribers-in-four-days/",
    "publishedAt": "2026-09-25T14:33:35.000Z",
    "snippet": "Annalisa Quinn’s story published Tuesday in The Boston Globe Magazine — “A Western Mass. lesbian bar required KN-95 masks. When it changed t"
  },
  {
    "sourceId": "angular-dev",
    "sourceName": "Angular.dev",
    "category": "technology",
    "title": "Architecting the Modern Web: Debounce APIs, Rendering Strategies, and Automated AI Setup! ⚡",
    "link": "https://blog.angular.dev/architecting-the-modern-web-debounce-apis-rendering-strategies-and-automated-ai-setup-826bc54ae3a9?source=rss----447683c3d9a3---4",
    "publishedAt": "2026-09-25T13:59:49.000Z",
    "snippet": "As we move deeper into the current release cycles, the Angular ecosystem is bringing incredibly refined primitives into our daily workflow. "
  },
  {
    "sourceId": "angular-dev",
    "sourceName": "Angular.dev",
    "category": "technology",
    "title": "An update on Angular’s TypeScript 7-powered Compiler",
    "link": "https://blog.angular.dev/an-update-on-angulars-typescript-7-powered-compiler-9619a35e2b0a?source=rss----447683c3d9a3---4",
    "publishedAt": "2026-09-25T13:59:11.000Z",
    "snippet": "Alex Rickabaugh & Mark Techson [Alex] I joined the Angular team in 2015, around the original Angular 2.0 release. One of my first tasks was "
  },
  {
    "sourceId": "the-marshall-project",
    "sourceName": "The Marshall Project",
    "category": "news",
    "title": "ICE Says It Can Detain Immigrants as Long as It Wants. Will the Supreme Court Agree?",
    "link": "https://www.themarshallproject.org/2026/09/25/ice-mandatory-detention-immigration-judges",
    "publishedAt": "2026-09-25T10:00:00.000Z",
    "snippet": "Hundreds of federal judges have ruled against the administration’s “mandatory detention” policy, but the Supreme Court may soon have the fin"
  },
  {
    "sourceId": "latent-space",
    "sourceName": "Latent Space",
    "category": "technology",
    "title": "[AINews] The Future of Latent Space",
    "link": "https://www.latent.space/p/ainews-the-future-of-latent-space",
    "publishedAt": "2026-09-25T05:37:00.000Z",
    "snippet": "A quiet day lets us discuss the work behind the scenes - now open for business!"
  },
  {
    "sourceId": "latent-space",
    "sourceName": "Latent Space",
    "category": "technology",
    "title": "Runway’s WorldPrompt and the Engineering of Real-Time Worlds",
    "link": "https://www.latent.space/p/runway",
    "publishedAt": "2026-09-25T01:30:57.000Z",
    "snippet": "GWM Worlds 2 uses persistent context and timed actions to steer a world model generating video and audio in real time."
  },
  {
    "sourceId": "hackaday-esp32",
    "sourceName": "Hackaday ESP32",
    "category": "technology",
    "title": "Handheld Scanner is a Radio Multi-tool",
    "link": "https://hackaday.com/2026/09/24/handheld-scanner-is-a-radio-multi-tool/",
    "publishedAt": "2026-09-24T18:30:05.000Z",
    "snippet": "These days, it’s possible to cram a whole lot of radio functionality into a very compact device. A great example of that is the LakeShark sc"
  },
  {
    "sourceId": "hackaday-esp32",
    "sourceName": "Hackaday ESP32",
    "category": "technology",
    "title": "Standalone DJ System Runs On ESP32",
    "link": "https://hackaday.com/2026/09/24/standalone-dj-system-runs-on-esp32/",
    "publishedAt": "2026-09-24T15:30:42.000Z",
    "snippet": "There are plenty of ways to DJ with a laptop and various controller setups. However, if you find hauling around an entire computer can be a "
  },
  {
    "sourceId": "latent-space",
    "sourceName": "Latent Space",
    "category": "technology",
    "title": "Foundries vs Navigators: Lowering the Cost of Science",
    "link": "https://www.latent.space/p/foundries-vs-navigators-lowering",
    "publishedAt": "2026-09-24T15:03:16.000Z",
    "snippet": "Guest Post: In science, thinking has gotten cheap but doing has not. This asymmetry is reshaping how research companies operate, largely inc"
  },
  {
    "sourceId": "hugging-face-blog",
    "sourceName": "Hugging Face Blog",
    "category": "technology",
    "title": "Accelerating vision-language models with LFM2.5-VL-DSpark",
    "link": "https://huggingface.co/blog/LiquidAI/lfm2-5-vl-dspark",
    "publishedAt": "2026-09-24T14:08:57.000Z",
    "snippet": ""
  },
  {
    "sourceId": "nieman-lab",
    "sourceName": "Nieman Lab",
    "category": "news",
    "title": "When disaster strikes, newsrooms scramble. A new website aims to help tame the chaos.",
    "link": "https://www.niemanlab.org/2026/09/when-disaster-strikes-newsrooms-scramble-a-new-website-aims-to-help-tame-the-chaos/",
    "publishedAt": "2026-09-24T13:44:47.000Z",
    "snippet": "On the day Hurricane Helene hit Western North Carolina in September 2024, Laura Lee was thousands of miles away on vacation in Peru. “I feel"
  },
  {
    "sourceId": "rest-of-world",
    "sourceName": "Rest of World",
    "category": "technology",
    "title": "China is excelling in health tech. That’s good news for the world",
    "link": "https://restofworld.org/2026/china-ai-healthcare-biotech-drugs/?utm_source=rss&utm_medium=rss&utm_campaign=feeds",
    "publishedAt": "2026-09-24T10:00:00.000Z",
    "snippet": "Ruby Wang, a physician and biotech consultant in the U.K., on her upcoming book on the emergence of China as a global health superpower."
  },
  {
    "sourceId": "latent-space",
    "sourceName": "Latent Space",
    "category": "technology",
    "title": "[AINews] Meta Connect 2026: Muse glasses, voice, video, and Charm",
    "link": "https://www.latent.space/p/ainews-meta-connect-2026-muse-glasses",
    "publishedAt": "2026-09-24T08:12:59.000Z",
    "snippet": "Team Zuck is absolutely on fire."
  },
  {
    "sourceId": "wikipedia",
    "sourceName": "Wikipedia",
    "category": "culture",
    "title": "September 24 Wikipedia featured article",
    "link": "https://en.wikipedia.org/wiki/Special:FeedItem/featured/20260924000000/en",
    "publishedAt": "2026-09-24T00:00:00.000Z",
    "snippet": "type=\"html\"><div class=\"mw-content-ltr mw-parser-output\" lang=\"en\" dir=\"ltr\"><div id=\"mp-tfa-img\" style=\"float: left; margin: 0.5em 0.9em 0."
  },
  {
    "sourceId": "lowtech",
    "sourceName": "Low Tech Magazine",
    "category": "culture",
    "title": "Out Now: Low-tech Magazine Volume IV",
    "link": "https://solar.lowtechmagazine.com/2026/09/out-now-low-tech-magazine-volume-iv/",
    "publishedAt": "2026-09-24T00:00:00.000Z",
    "snippet": "<div class=\"article-img \"> <figure data-imgstate=\"dither\"> <img src=\"https://solar.lowtechmagazine.com/2026/09/out-now-low-tech-magazine-vol"
  },
  {
    "sourceId": "hugging-face-blog",
    "sourceName": "Hugging Face Blog",
    "category": "technology",
    "title": "How to Use NVIDIA Warp and MjWarp to Accelerate Robotics Simulation and Learning Workflows",
    "link": "https://huggingface.co/blog/nvidia/how-to-use-nvidia-warp-and-mjwarp",
    "publishedAt": "2026-09-23T18:41:40.000Z",
    "snippet": ""
  },
  {
    "sourceId": "icij",
    "sourceName": "ICIJ",
    "category": "news",
    "title": "China Capital stories reveal how ICBC advanced China’s political goals across four continents",
    "link": "https://www.icij.org/investigations/china-capital/china-capital-stories-reveal-how-icbc-advanced-chinas-political-goals-across-four-continents/",
    "publishedAt": "2026-09-23T18:29:54.000Z",
    "snippet": "ICIJ’s media partners uncovered strategic deals and moves the Chinese bank made around the world to further the political priorities of the "
  }
] as const;
