import { Source } from './source.model';

/**
 * Hand-authored `Source` records (D1 — a typed fixture, not a `sources/`
 * YAML-plus-build pipeline). Five groups, per the plan's "Seed content"
 * section:
 *
 *   1. AI skill marketplaces (`category: 'ai-marketplace'`)
 *   2. Open-web holdouts
 *   3. Developer reference
 *   4. News (European mainstream + open-source/investigative)
 *   5. Inspiration and things worth finding
 *
 * `desc`, `trustScore`, `capabilities`, `tags` and `verified` are editorial
 * heuristics assigned at authoring time (plan: "AI-assigned... reasonable
 * and consistent judgment is the bar, not precision"), not measurements.
 * Group 1's descriptions and verification dates are copied from
 * `JooKoi-developer-stack/ai-tooling-crash-course-for-developers/_ai-tooling-recommendations.md`,
 * which was reachable from this machine at authoring time.
 *
 * This is a first pass (plan: "deeper curation passes are expected"). The
 * earlier mockup content and the `estonia` tag lean Estonian, this session's
 * steer leaned Danish — both are represented, per the plan's explicit call
 * that no single-region resolution is needed here.
 */
export const SOURCE_FIXTURE: readonly Source[] = [
  // ---------------------------------------------------------------------
  // 1. AI skill marketplaces
  // ---------------------------------------------------------------------
  {
    id: 'mdskills-ai',
    name: 'mdskills.ai',
    url: 'https://www.mdskills.ai',
    desc: 'Skill, plugin and MCP-server marketplace with 4,000+ listings and visible download counts.',
    type: 'AI skill marketplace',
    category: 'ai-marketplace',
    tags: ['ai-tooling', 'skills', 'mcp', 'marketplace'],
    trustScore: 60,
    capabilities: ['site-search'],
    verified: '2026-08-22',
    lang: 'en',
  },
  {
    id: 'agensi-io',
    name: 'Agensi',
    url: 'https://www.agensi.io',
    desc: "Cross-tool paid skills marketplace with 4,000+ listings; hosts real free skills like git-commit-writer and pr-description-writer alongside self-reported 'most downloaded' claims.",
    type: 'AI skill marketplace',
    category: 'ai-marketplace',
    tags: ['ai-tooling', 'skills', 'marketplace'],
    trustScore: 58,
    capabilities: ['site-search'],
    verified: '2026-08-22',
    lang: 'en',
  },
  {
    id: 'mcpmarket-com',
    name: 'MCP Market',
    url: 'https://mcpmarket.com',
    desc: "Numbered leaderboard of atomic single-purpose skills and MCP servers, ranked by the GitHub star count of each entry's underlying repo — a confirmed methodology, not a self-reported metric.",
    type: 'AI skill marketplace',
    category: 'ai-marketplace',
    tags: ['ai-tooling', 'skills', 'mcp', 'leaderboard'],
    trustScore: 68,
    capabilities: ['site-search'],
    verified: '2026-08-22',
    lang: 'en',
  },
  {
    id: 'gh-obra-superpowers',
    name: 'obra/superpowers',
    url: 'https://github.com/obra/superpowers',
    desc: 'Agentic skills framework and plan-first, spec-driven development methodology — brainstorming, writing-plans, TDD, verification.',
    type: 'Skill library repo',
    category: 'ai-marketplace',
    tags: ['ai-tooling', 'skills', 'github', 'workflow'],
    trustScore: 88,
    capabilities: ['rss-feed', 'site-search', 'public-api'],
    verified: '2026-08-22',
    lang: 'en',
  },
  {
    id: 'gh-addyosmani-agent-skills',
    name: 'addyosmani/agent-skills',
    url: 'https://github.com/addyosmani/agent-skills',
    desc: '24 production-grade engineering skills for AI coding agents — spec-driven dev, TDD, code review, performance optimisation, Chrome DevTools browser testing. Maintainer Addy Osmani is a named, checkable web-performance practitioner.',
    type: 'Skill library repo',
    category: 'ai-marketplace',
    tags: ['ai-tooling', 'skills', 'github', 'performance'],
    trustScore: 90,
    capabilities: ['rss-feed', 'site-search', 'public-api'],
    verified: '2026-08-22',
    lang: 'en',
  },
  {
    id: 'gh-mattpocock-skills',
    name: 'mattpocock/skills',
    url: 'https://github.com/mattpocock/skills',
    desc: '"Skills for Real Engineers" — personal collection from Matt Pocock, a well-known TypeScript educator, including strict-interrogation and TDD-style workflow skills.',
    type: 'Skill library repo',
    category: 'ai-marketplace',
    tags: ['ai-tooling', 'skills', 'github', 'typescript'],
    trustScore: 85,
    capabilities: ['rss-feed', 'site-search', 'public-api'],
    verified: '2026-08-22',
    lang: 'en',
  },
  {
    id: 'gh-vercel-labs-agent-skills',
    name: 'vercel-labs/agent-skills',
    url: 'https://github.com/vercel-labs/agent-skills',
    desc: "Vercel's structural guidelines and skill trees for web-design and framework conventions, including Next.js and React Server Component patterns.",
    type: 'Skill library repo',
    category: 'ai-marketplace',
    tags: ['ai-tooling', 'skills', 'github', 'frontend'],
    trustScore: 88,
    capabilities: ['rss-feed', 'site-search', 'public-api'],
    verified: '2026-08-22',
    lang: 'en',
  },
  {
    id: 'gh-cloudflare-skills',
    name: 'cloudflare/skills',
    url: 'https://github.com/cloudflare/skills',
    desc: 'Official Cloudflare Agent Skills repo, including a web-perf skill covering Core Web Vitals, LCP/INP/CLS and Lighthouse auditing guidance.',
    type: 'Skill library repo',
    category: 'ai-marketplace',
    tags: ['ai-tooling', 'skills', 'github', 'performance'],
    trustScore: 90,
    capabilities: ['rss-feed', 'site-search', 'public-api'],
    verified: '2026-08-23',
    lang: 'en',
  },

  // ---------------------------------------------------------------------
  // 2. Open-web holdouts
  // ---------------------------------------------------------------------
  {
    id: 'wikipedia',
    name: 'Wikipedia',
    url: 'https://www.wikipedia.org',
    desc: 'Collaboratively edited free encyclopedia — the largest reference work on the open web.',
    type: 'Encyclopedia',
    category: 'open-web',
    tags: ['reference', 'encyclopedia', 'no-tracking'],
    trustScore: 88,
    capabilities: ['rss-feed', 'site-search', 'public-api'],
    verified: '2026-08-20',
    searchUrl: 'https://en.wikipedia.org/w/index.php?search={q}',
    lang: 'en',
  },
  {
    id: 'internet-archive',
    name: 'Internet Archive',
    url: 'https://archive.org',
    desc: 'Non-profit digital library preserving web pages, books, audio and video — home of the Wayback Machine.',
    type: 'Web archive',
    category: 'open-web',
    tags: ['archive', 'preservation', 'no-tracking'],
    trustScore: 90,
    capabilities: ['rss-feed', 'site-search', 'public-api'],
    verified: '2026-08-19',
    searchUrl: 'https://archive.org/search?query={q}',
    lang: 'en',
  },
  {
    id: 'marginalia-search',
    name: 'Marginalia Search',
    url: 'https://marginalia-search.com',
    desc: 'Independent search engine that favours small, text-heavy sites.',
    type: 'Search engine',
    category: 'open-web',
    tags: ['search-engine', 'small-web', 'no-tracking'],
    trustScore: 82,
    capabilities: ['site-search', 'public-api'],
    verified: '2026-08-21',
    searchUrl: 'https://old-search.marginalia.nu/search?query={q}',
    lang: 'en',
  },
  {
    id: 'arxiv',
    name: 'arXiv',
    url: 'https://arxiv.org',
    desc: 'Open-access preprints in physics, maths and computer science.',
    type: 'Preprint archive',
    category: 'open-web',
    tags: ['preprints', 'science', 'open-access'],
    trustScore: 92,
    capabilities: ['rss-feed', 'site-search', 'public-api'],
    verified: '2026-08-18',
    searchUrl: 'https://arxiv.org/abs/{q}',
    lang: 'en',
  },
  {
    id: 'hacker-news',
    name: 'Hacker News',
    url: 'https://news.ycombinator.com',
    desc: 'Tech-and-startup link aggregator and discussion board run by Y Combinator.',
    type: 'Link aggregator',
    category: 'open-web',
    tags: ['tech-news', 'discussion', 'small-web'],
    trustScore: 74,
    capabilities: ['site-search', 'public-api'],
    verified: '2026-08-25',
    searchUrl: 'https://hn.algolia.com/?q={q}',
    lang: 'en',
  },
  {
    id: 'public-domain-review',
    name: 'Public Domain Review',
    url: 'https://publicdomainreview.org',
    desc: 'Curated essays and collections drawn from out-of-copyright art, books and film.',
    type: 'Curated archive essays',
    category: 'open-web',
    tags: ['public-domain', 'archive', 'curiosity'],
    trustScore: 80,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-08-24',
    lang: 'en',
  },
  {
    id: 'low-tech-magazine',
    name: 'Low-tech Magazine',
    url: 'https://www.lowtechmagazine.com',
    desc: 'Independent magazine on sustainable technology and appropriate-tech design, hosted on a solar-powered server.',
    type: 'Independent magazine',
    category: 'open-web',
    tags: ['sustainability', 'small-web', 'no-tracking'],
    trustScore: 80,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-08-27',
    lang: 'en',
  },

  // ---------------------------------------------------------------------
  // 3. Developer reference
  // ---------------------------------------------------------------------
  {
    id: 'mdn',
    name: 'MDN Web Docs',
    url: 'https://developer.mozilla.org',
    desc: 'Reference for HTML, CSS, JavaScript and Web APIs.',
    type: 'Reference',
    category: 'developer-reference',
    tags: ['html', 'css', 'javascript', 'web-apis'],
    trustScore: 92,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-09-02',
    searchUrl: 'https://developer.mozilla.org/en-US/search?q={q}',
    lang: 'en',
  },
  {
    id: 'devdocs',
    name: 'DevDocs',
    url: 'https://devdocs.io',
    desc: 'Fast, offline-capable API documentation browser aggregating dozens of language and framework references in one interface.',
    type: 'Offline docs aggregator',
    category: 'developer-reference',
    tags: ['reference', 'offline', 'aggregator'],
    trustScore: 82,
    capabilities: ['site-search'],
    verified: '2026-08-30',
    lang: 'en',
  },
  {
    id: 'caniuse',
    name: 'Can I Use',
    url: 'https://caniuse.com',
    desc: 'Up-to-date browser support tables for HTML, CSS and JavaScript features.',
    type: 'Browser support tables',
    category: 'developer-reference',
    tags: ['browser-support', 'compatibility', 'css'],
    trustScore: 88,
    capabilities: ['site-search', 'public-api'],
    verified: '2026-08-29',
    lang: 'en',
  },
  {
    id: 'tc39-proposals',
    name: 'TC39 Proposals',
    url: 'https://github.com/tc39/proposals',
    desc: 'Live tracker of JavaScript language proposals moving through the TC39 standards process.',
    type: 'Standards proposal tracker',
    category: 'developer-reference',
    tags: ['javascript', 'standards', 'tc39'],
    trustScore: 90,
    capabilities: ['rss-feed', 'site-search', 'public-api'],
    verified: '2026-09-01',
    lang: 'en',
  },
  {
    id: 'w3c',
    name: 'W3C',
    url: 'https://www.w3.org',
    desc: 'Standards body publishing the specifications the open web is built on.',
    type: 'Standards body',
    category: 'developer-reference',
    tags: ['standards', 'web-platform'],
    trustScore: 90,
    capabilities: ['site-search'],
    verified: '2026-08-15',
    lang: 'en',
  },
  {
    id: 'typescript-handbook',
    name: 'TypeScript Handbook',
    url: 'https://www.typescriptlang.org/docs/handbook/intro.html',
    desc: 'Official language reference and handbook for TypeScript.',
    type: 'Language reference',
    category: 'developer-reference',
    tags: ['typescript', 'reference'],
    trustScore: 90,
    capabilities: ['site-search'],
    verified: '2026-09-05',
    lang: 'en',
  },
  {
    id: 'nodejs-docs',
    name: 'Node.js Docs',
    url: 'https://nodejs.org/docs/latest/api/',
    desc: 'Official API reference and release documentation for the Node.js runtime.',
    type: 'Runtime reference',
    category: 'developer-reference',
    tags: ['nodejs', 'javascript', 'runtime'],
    trustScore: 90,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-09-03',
    lang: 'en',
  },
  {
    id: 'stack-overflow',
    name: 'Stack Overflow',
    url: 'https://stackoverflow.com',
    desc: 'Question-and-answer community for programming problems, with a well-documented public API.',
    type: 'Q&A community',
    category: 'developer-reference',
    tags: ['qa', 'community', 'troubleshooting'],
    trustScore: 76,
    capabilities: ['site-search', 'public-api'],
    verified: '2026-08-31',
    searchUrl: 'https://stackoverflow.com/search?q={q}',
    lang: 'en',
  },

  // ---------------------------------------------------------------------
  // 4. News — European mainstream + open-source/investigative
  // ---------------------------------------------------------------------
  {
    id: 'dr-dk',
    name: 'DR',
    url: 'https://www.dr.dk',
    desc: "Denmark's public-service broadcaster and one of its largest news operations.",
    type: 'Public-service broadcaster',
    category: 'news',
    tags: ['news', 'public-service', 'denmark'],
    trustScore: 88,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-08-26',
    lang: 'da',
    region: 'Denmark',
  },
  {
    id: 'politiken',
    name: 'Politiken',
    url: 'https://politiken.dk',
    desc: 'Long-running Danish quality-press daily newspaper.',
    type: 'Quality press',
    category: 'news',
    tags: ['news', 'denmark'],
    trustScore: 84,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-08-26',
    lang: 'da',
    region: 'Denmark',
  },
  {
    id: 'yle',
    name: 'Yle',
    url: 'https://yle.fi',
    desc: "Finland's public-service broadcaster, including an English-language news service.",
    type: 'Public-service broadcaster',
    category: 'news',
    tags: ['news', 'public-service', 'finland'],
    trustScore: 88,
    capabilities: ['rss-feed', 'site-search', 'public-api'],
    verified: '2026-08-26',
    lang: 'fi',
    region: 'Finland',
  },
  {
    id: 'svt',
    name: 'SVT',
    url: 'https://www.svt.se',
    desc: "Sweden's public-service television broadcaster and news site.",
    type: 'Public-service broadcaster',
    category: 'news',
    tags: ['news', 'public-service', 'sweden'],
    trustScore: 87,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-08-26',
    lang: 'sv',
    region: 'Sweden',
  },
  {
    id: 'nrk',
    name: 'NRK',
    url: 'https://www.nrk.no',
    desc: "Norway's public-service broadcaster and largest news organisation.",
    type: 'Public-service broadcaster',
    category: 'news',
    tags: ['news', 'public-service', 'norway'],
    trustScore: 88,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-08-26',
    lang: 'no',
    region: 'Norway',
  },
  {
    id: 'err-news',
    name: 'ERR News',
    url: 'https://news.err.ee',
    desc: 'Estonian public broadcaster, English-language news desk.',
    type: 'News',
    category: 'news',
    tags: ['news', 'estonia'],
    trustScore: 86,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-08-29',
    lang: 'en',
    region: 'Estonia',
  },
  {
    id: 'der-spiegel',
    name: 'Der Spiegel',
    url: 'https://www.spiegel.de',
    desc: "One of Germany's largest and most influential weekly news magazines.",
    type: 'Quality press',
    category: 'news',
    tags: ['news', 'germany'],
    trustScore: 85,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-08-27',
    lang: 'de',
    region: 'Germany',
  },
  {
    id: 'le-monde',
    name: 'Le Monde',
    url: 'https://www.lemonde.fr',
    desc: "France's paper of record and a leading European quality daily.",
    type: 'Quality press',
    category: 'news',
    tags: ['news', 'france'],
    trustScore: 86,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-08-27',
    lang: 'fr',
    region: 'France',
  },
  {
    id: 'nrc',
    name: 'NRC',
    url: 'https://www.nrc.nl',
    desc: 'Dutch quality daily newspaper known for its investigative and business coverage.',
    type: 'Quality press',
    category: 'news',
    tags: ['news', 'netherlands'],
    trustScore: 84,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-08-28',
    lang: 'nl',
    region: 'Netherlands',
  },
  {
    id: 'the-guardian',
    name: 'The Guardian',
    url: 'https://www.theguardian.com',
    desc: 'British quality daily with a large international desk and a public Open Platform content API.',
    type: 'Quality press',
    category: 'news',
    tags: ['news', 'united-kingdom'],
    trustScore: 86,
    capabilities: ['rss-feed', 'site-search', 'public-api'],
    verified: '2026-08-28',
    lang: 'en',
    region: 'United Kingdom',
  },
  {
    id: 'euronews',
    name: 'Euronews',
    url: 'https://www.euronews.com',
    desc: 'Pan-European news channel and site covering EU and continent-wide affairs.',
    type: 'Pan-European news',
    category: 'news',
    tags: ['news', 'europe'],
    trustScore: 78,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-08-30',
    lang: 'en',
    region: 'Europe',
  },
  {
    id: 'bellingcat',
    name: 'Bellingcat',
    url: 'https://www.bellingcat.com',
    desc: 'Open-source investigation collective — the literal case of using open web data to verify events others deny.',
    type: 'Open-source investigative outlet',
    category: 'news',
    tags: ['investigative', 'open-source-research'],
    trustScore: 92,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-09-01',
    lang: 'en',
    region: 'Global',
  },
  {
    id: 'occrp',
    name: 'OCCRP',
    url: 'https://www.occrp.org',
    desc: 'Organized Crime and Corruption Reporting Project — cross-border investigative journalism network, with a public investigative-data API (Aleph).',
    type: 'Open-source investigative outlet',
    category: 'news',
    tags: ['investigative', 'corruption', 'data-journalism'],
    trustScore: 90,
    capabilities: ['rss-feed', 'site-search', 'public-api'],
    verified: '2026-09-01',
    lang: 'en',
    region: 'Global',
  },
  {
    id: 'correctiv',
    name: 'Correctiv',
    url: 'https://correctiv.org',
    desc: "Germany's first non-profit investigative newsroom.",
    type: 'Open-source investigative outlet',
    category: 'news',
    tags: ['investigative', 'germany'],
    trustScore: 85,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-09-02',
    lang: 'de',
    region: 'Germany',
  },
  {
    id: 'follow-the-money',
    name: 'Follow the Money',
    url: 'https://www.ftm.eu',
    desc: 'Dutch investigative platform funded by its readers, focused on money and power.',
    type: 'Open-source investigative outlet',
    category: 'news',
    tags: ['investigative', 'netherlands'],
    trustScore: 82,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-09-02',
    lang: 'nl',
    region: 'Netherlands',
  },
  {
    id: 'danwatch',
    name: 'Danwatch',
    url: 'https://danwatch.dk',
    desc: 'Danish independent media covering human rights, environment and responsible business.',
    type: 'Open-source investigative outlet',
    category: 'news',
    tags: ['investigative', 'denmark'],
    trustScore: 80,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-09-03',
    lang: 'da',
    region: 'Denmark',
  },
  {
    id: 'investigate-europe',
    name: 'Investigate Europe',
    url: 'https://www.investigate-europe.eu',
    desc: 'Cross-border European team of investigative reporters working stories no single newsroom could cover alone.',
    type: 'Open-source investigative outlet',
    category: 'news',
    tags: ['investigative', 'europe'],
    trustScore: 82,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-09-03',
    lang: 'en',
    region: 'Europe',
  },
  {
    id: 'propublica',
    name: 'ProPublica',
    url: 'https://www.propublica.org',
    desc: 'Pulitzer-winning US non-profit newsroom for investigative journalism, with a well-documented public data API.',
    type: 'Open-source investigative outlet',
    category: 'news',
    tags: ['investigative', 'united-states'],
    trustScore: 90,
    capabilities: ['rss-feed', 'site-search', 'public-api'],
    verified: '2026-09-04',
    lang: 'en',
    region: 'United States',
  },

  // ---------------------------------------------------------------------
  // 5. Inspiration and things worth finding
  // ---------------------------------------------------------------------
  {
    id: 'smashing-magazine',
    name: 'Smashing Magazine',
    url: 'https://www.smashingmagazine.com',
    desc: 'Long-running magazine on front-end development, UX and design craft.',
    type: 'Design & dev magazine',
    category: 'inspiration',
    tags: ['design', 'frontend', 'css'],
    trustScore: 85,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-09-06',
    lang: 'en',
  },
  {
    id: 'a-list-apart',
    name: 'A List Apart',
    url: 'https://alistapart.com',
    desc: 'One of the formative web-standards and web-design publications, still publishing.',
    type: 'Web design magazine',
    category: 'inspiration',
    tags: ['design', 'web-standards'],
    trustScore: 80,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-09-06',
    lang: 'en',
  },
  {
    id: 'are-na',
    name: 'Are.na',
    url: 'https://www.are.na',
    desc: 'Slow, ad-free visual research and collaborative bookmarking platform, with a public API.',
    type: 'Visual research platform',
    category: 'inspiration',
    tags: ['curation', 'visual-research', 'small-web'],
    trustScore: 78,
    capabilities: ['site-search', 'public-api'],
    verified: '2026-09-07',
    lang: 'en',
  },
  {
    id: 'its-nice-that',
    name: "It's Nice That",
    url: 'https://www.itsnicethat.com',
    desc: 'Creative culture magazine covering graphic design, illustration and art.',
    type: 'Creative culture magazine',
    category: 'inspiration',
    tags: ['design', 'art', 'culture'],
    trustScore: 78,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-09-07',
    lang: 'en',
  },
  {
    id: 'atlas-obscura',
    name: 'Atlas Obscura',
    url: 'https://www.atlasobscura.com',
    desc: 'Curiosity-and-travel encyclopedia of unusual places worth knowing about.',
    type: 'Curiosity & travel encyclopedia',
    category: 'inspiration',
    tags: ['curiosity', 'places', 'travel'],
    trustScore: 80,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-09-08',
    lang: 'en',
  },
  {
    id: 'colossal',
    name: 'Colossal',
    url: 'https://www.thisiscolossal.com',
    desc: 'Art and design blog covering illustration, sculpture and installation work worldwide.',
    type: 'Art & design blog',
    category: 'inspiration',
    tags: ['art', 'design', 'culture'],
    trustScore: 78,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-09-08',
    lang: 'en',
  },
  {
    id: 'positive-news',
    name: 'Positive News',
    url: 'https://www.positive.news',
    desc: 'Constructive-journalism magazine reporting on progress alongside the news.',
    type: 'Constructive journalism magazine',
    category: 'inspiration',
    tags: ['positive-news', 'constructive-journalism'],
    trustScore: 75,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-09-09',
    lang: 'en',
  },
  {
    id: 'reasons-to-be-cheerful',
    name: 'Reasons to be Cheerful',
    url: 'https://reasonstobecheerful.world',
    desc: 'Solutions-journalism magazine covering ideas that are working, founded by David Byrne.',
    type: 'Solutions journalism magazine',
    category: 'inspiration',
    tags: ['solutions-journalism', 'positive-news'],
    trustScore: 76,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-09-09',
    lang: 'en',
  },
  {
    id: 'kottke',
    name: 'kottke.org',
    url: 'https://kottke.org',
    desc: 'One of the longest-running personal link blogs on the web, curating the interesting and overlooked.',
    type: 'Personal link blog',
    category: 'inspiration',
    tags: ['blog', 'link-blog', 'small-web'],
    trustScore: 74,
    capabilities: ['rss-feed', 'site-search'],
    verified: '2026-09-10',
    lang: 'en',
  },
];
