// Generated by scripts/build-library-content.mjs. Committed (R2 amends
// decision 022) — a fresh clone builds without running the generator.
// Regenerate by hand after content changes: `pnpm run content`.
export interface LibraryDocMeta {
  readonly path: string;
  readonly title: string;
  readonly order: number;
  readonly summary: string;
  readonly tags: readonly string[];
  readonly hasDiagrams: boolean;
  readonly prev: string | null;
  readonly next: string | null;
}

export interface LibraryCollectionSummary {
  readonly path: string;
  readonly title: string;
  readonly summary: string;
  readonly docCount: number;
}

export interface LibraryDocRedirect {
  readonly from: string;
  readonly to: string;
}

export interface LibraryFolderMeta {
  readonly path: string;
  readonly title: string;
  readonly order: number;
  readonly summary: string;
  readonly introHtml: string;
  readonly childFolders: readonly string[];
  readonly docs: readonly string[];
  readonly docCount: number;
  readonly collections?: readonly LibraryCollectionSummary[];
}

export const LIBRARY_ROOT: LibraryFolderMeta = {
  "path": "",
  "title": "Library",
  "order": 0,
  "summary": "",
  "introHtml": "",
  "childFolders": [
    "ai-tooling-crash-course-for-developers"
  ],
  "docs": [],
  "docCount": 23,
  "collections": [
    {
      "path": "ai-tooling-crash-course-for-developers",
      "title": "AI Tooling Crash Course for Developers",
      "summary": "AI tooling crash course and topic notes.",
      "docCount": 23
    }
  ]
};

export const LIBRARY_FOLDERS: readonly LibraryFolderMeta[] = [
  {
    "path": "ai-tooling-crash-course-for-developers",
    "title": "AI Tooling Crash Course for Developers",
    "order": 0,
    "summary": "AI tooling crash course and topic notes.",
    "introHtml": "<p>Notes and deep-dives on AI-assisted development. Open a file from the tree, or browse <code>topics/</code>.</p>\n",
    "childFolders": [
      "ai-tooling-crash-course-for-developers/topics"
    ],
    "docs": [
      "ai-tooling-crash-course-for-developers/_ai-tooling-recommendations",
      "ai-tooling-crash-course-for-developers/_inspiration-and-staying-current",
      "ai-tooling-crash-course-for-developers/0-how-llms-actually-work-under-the-hood",
      "ai-tooling-crash-course-for-developers/README"
    ],
    "docCount": 23
  },
  {
    "path": "ai-tooling-crash-course-for-developers/topics",
    "title": "Topics",
    "order": 0,
    "summary": "",
    "introHtml": "",
    "childFolders": [],
    "docs": [
      "ai-tooling-crash-course-for-developers/topics/agent-sandboxing",
      "ai-tooling-crash-course-for-developers/topics/base-instruction-files",
      "ai-tooling-crash-course-for-developers/topics/dev-scoped-second-brain-rag",
      "ai-tooling-crash-course-for-developers/topics/graph-engineering-multi-agent-coordination",
      "ai-tooling-crash-course-for-developers/topics/harness-engineering-vocabulary",
      "ai-tooling-crash-course-for-developers/topics/local-model-hardware-fit",
      "ai-tooling-crash-course-for-developers/topics/loop-engineering-agent-loops",
      "ai-tooling-crash-course-for-developers/topics/mcp-model-context-protocol",
      "ai-tooling-crash-course-for-developers/topics/memory-and-progress-ledgers",
      "ai-tooling-crash-course-for-developers/topics/personal-harness-architecture",
      "ai-tooling-crash-course-for-developers/topics/planning-before-implementation",
      "ai-tooling-crash-course-for-developers/topics/prompt-engineering",
      "ai-tooling-crash-course-for-developers/topics/protocol-landscape-acp-a2a",
      "ai-tooling-crash-course-for-developers/topics/review-and-verification-tooling",
      "ai-tooling-crash-course-for-developers/topics/security-and-supply-chain",
      "ai-tooling-crash-course-for-developers/topics/session-and-token-economics",
      "ai-tooling-crash-course-for-developers/topics/skill-libraries-and-marketplaces",
      "ai-tooling-crash-course-for-developers/topics/skill-scanning-and-verification",
      "ai-tooling-crash-course-for-developers/topics/subagents-and-delegation"
    ],
    "docCount": 19
  }
];

export const LIBRARY_DOCS: readonly LibraryDocMeta[] = [
  {
    "path": "ai-tooling-crash-course-for-developers/_ai-tooling-recommendations",
    "title": "Ai Tooling Recommendations",
    "order": 0,
    "summary": "",
    "tags": [],
    "hasDiagrams": false,
    "prev": null,
    "next": "ai-tooling-crash-course-for-developers/_inspiration-and-staying-current"
  },
  {
    "path": "ai-tooling-crash-course-for-developers/_inspiration-and-staying-current",
    "title": "Inspiration And Staying Current",
    "order": 0,
    "summary": "",
    "tags": [],
    "hasDiagrams": false,
    "prev": "ai-tooling-crash-course-for-developers/_ai-tooling-recommendations",
    "next": "ai-tooling-crash-course-for-developers/0-how-llms-actually-work-under-the-hood"
  },
  {
    "path": "ai-tooling-crash-course-for-developers/0-how-llms-actually-work-under-the-hood",
    "title": "0 How Llms Actually Work Under The Hood",
    "order": 0,
    "summary": "",
    "tags": [],
    "hasDiagrams": false,
    "prev": "ai-tooling-crash-course-for-developers/_inspiration-and-staying-current",
    "next": "ai-tooling-crash-course-for-developers/README"
  },
  {
    "path": "ai-tooling-crash-course-for-developers/README",
    "title": "README",
    "order": 0,
    "summary": "",
    "tags": [],
    "hasDiagrams": false,
    "prev": "ai-tooling-crash-course-for-developers/0-how-llms-actually-work-under-the-hood",
    "next": null
  },
  {
    "path": "ai-tooling-crash-course-for-developers/topics/agent-sandboxing",
    "title": "Agent Sandboxing",
    "order": 0,
    "summary": "",
    "tags": [],
    "hasDiagrams": false,
    "prev": null,
    "next": "ai-tooling-crash-course-for-developers/topics/base-instruction-files"
  },
  {
    "path": "ai-tooling-crash-course-for-developers/topics/base-instruction-files",
    "title": "Base Instruction Files",
    "order": 0,
    "summary": "",
    "tags": [],
    "hasDiagrams": false,
    "prev": "ai-tooling-crash-course-for-developers/topics/agent-sandboxing",
    "next": "ai-tooling-crash-course-for-developers/topics/dev-scoped-second-brain-rag"
  },
  {
    "path": "ai-tooling-crash-course-for-developers/topics/dev-scoped-second-brain-rag",
    "title": "Dev Scoped Second Brain Rag",
    "order": 0,
    "summary": "",
    "tags": [],
    "hasDiagrams": false,
    "prev": "ai-tooling-crash-course-for-developers/topics/base-instruction-files",
    "next": "ai-tooling-crash-course-for-developers/topics/graph-engineering-multi-agent-coordination"
  },
  {
    "path": "ai-tooling-crash-course-for-developers/topics/graph-engineering-multi-agent-coordination",
    "title": "Graph Engineering Multi Agent Coordination",
    "order": 0,
    "summary": "",
    "tags": [],
    "hasDiagrams": false,
    "prev": "ai-tooling-crash-course-for-developers/topics/dev-scoped-second-brain-rag",
    "next": "ai-tooling-crash-course-for-developers/topics/harness-engineering-vocabulary"
  },
  {
    "path": "ai-tooling-crash-course-for-developers/topics/harness-engineering-vocabulary",
    "title": "Harness Engineering Vocabulary",
    "order": 0,
    "summary": "",
    "tags": [],
    "hasDiagrams": false,
    "prev": "ai-tooling-crash-course-for-developers/topics/graph-engineering-multi-agent-coordination",
    "next": "ai-tooling-crash-course-for-developers/topics/local-model-hardware-fit"
  },
  {
    "path": "ai-tooling-crash-course-for-developers/topics/local-model-hardware-fit",
    "title": "Local Model Hardware Fit",
    "order": 0,
    "summary": "",
    "tags": [],
    "hasDiagrams": false,
    "prev": "ai-tooling-crash-course-for-developers/topics/harness-engineering-vocabulary",
    "next": "ai-tooling-crash-course-for-developers/topics/loop-engineering-agent-loops"
  },
  {
    "path": "ai-tooling-crash-course-for-developers/topics/loop-engineering-agent-loops",
    "title": "Loop Engineering Agent Loops",
    "order": 0,
    "summary": "",
    "tags": [],
    "hasDiagrams": false,
    "prev": "ai-tooling-crash-course-for-developers/topics/local-model-hardware-fit",
    "next": "ai-tooling-crash-course-for-developers/topics/mcp-model-context-protocol"
  },
  {
    "path": "ai-tooling-crash-course-for-developers/topics/mcp-model-context-protocol",
    "title": "Mcp Model Context Protocol",
    "order": 0,
    "summary": "",
    "tags": [],
    "hasDiagrams": false,
    "prev": "ai-tooling-crash-course-for-developers/topics/loop-engineering-agent-loops",
    "next": "ai-tooling-crash-course-for-developers/topics/memory-and-progress-ledgers"
  },
  {
    "path": "ai-tooling-crash-course-for-developers/topics/memory-and-progress-ledgers",
    "title": "Memory And Progress Ledgers",
    "order": 0,
    "summary": "",
    "tags": [],
    "hasDiagrams": false,
    "prev": "ai-tooling-crash-course-for-developers/topics/mcp-model-context-protocol",
    "next": "ai-tooling-crash-course-for-developers/topics/personal-harness-architecture"
  },
  {
    "path": "ai-tooling-crash-course-for-developers/topics/personal-harness-architecture",
    "title": "Personal Harness Architecture",
    "order": 0,
    "summary": "",
    "tags": [],
    "hasDiagrams": false,
    "prev": "ai-tooling-crash-course-for-developers/topics/memory-and-progress-ledgers",
    "next": "ai-tooling-crash-course-for-developers/topics/planning-before-implementation"
  },
  {
    "path": "ai-tooling-crash-course-for-developers/topics/planning-before-implementation",
    "title": "Planning Before Implementation",
    "order": 0,
    "summary": "",
    "tags": [],
    "hasDiagrams": false,
    "prev": "ai-tooling-crash-course-for-developers/topics/personal-harness-architecture",
    "next": "ai-tooling-crash-course-for-developers/topics/prompt-engineering"
  },
  {
    "path": "ai-tooling-crash-course-for-developers/topics/prompt-engineering",
    "title": "Prompt Engineering",
    "order": 0,
    "summary": "",
    "tags": [],
    "hasDiagrams": false,
    "prev": "ai-tooling-crash-course-for-developers/topics/planning-before-implementation",
    "next": "ai-tooling-crash-course-for-developers/topics/protocol-landscape-acp-a2a"
  },
  {
    "path": "ai-tooling-crash-course-for-developers/topics/protocol-landscape-acp-a2a",
    "title": "Protocol Landscape Acp A2a",
    "order": 0,
    "summary": "",
    "tags": [],
    "hasDiagrams": false,
    "prev": "ai-tooling-crash-course-for-developers/topics/prompt-engineering",
    "next": "ai-tooling-crash-course-for-developers/topics/review-and-verification-tooling"
  },
  {
    "path": "ai-tooling-crash-course-for-developers/topics/review-and-verification-tooling",
    "title": "Review And Verification Tooling",
    "order": 0,
    "summary": "",
    "tags": [],
    "hasDiagrams": false,
    "prev": "ai-tooling-crash-course-for-developers/topics/protocol-landscape-acp-a2a",
    "next": "ai-tooling-crash-course-for-developers/topics/security-and-supply-chain"
  },
  {
    "path": "ai-tooling-crash-course-for-developers/topics/security-and-supply-chain",
    "title": "Security And Supply Chain",
    "order": 0,
    "summary": "",
    "tags": [],
    "hasDiagrams": false,
    "prev": "ai-tooling-crash-course-for-developers/topics/review-and-verification-tooling",
    "next": "ai-tooling-crash-course-for-developers/topics/session-and-token-economics"
  },
  {
    "path": "ai-tooling-crash-course-for-developers/topics/session-and-token-economics",
    "title": "Session And Token Economics",
    "order": 0,
    "summary": "",
    "tags": [],
    "hasDiagrams": false,
    "prev": "ai-tooling-crash-course-for-developers/topics/security-and-supply-chain",
    "next": "ai-tooling-crash-course-for-developers/topics/skill-libraries-and-marketplaces"
  },
  {
    "path": "ai-tooling-crash-course-for-developers/topics/skill-libraries-and-marketplaces",
    "title": "Skill Libraries And Marketplaces",
    "order": 0,
    "summary": "",
    "tags": [],
    "hasDiagrams": false,
    "prev": "ai-tooling-crash-course-for-developers/topics/session-and-token-economics",
    "next": "ai-tooling-crash-course-for-developers/topics/skill-scanning-and-verification"
  },
  {
    "path": "ai-tooling-crash-course-for-developers/topics/skill-scanning-and-verification",
    "title": "Skill Scanning And Verification",
    "order": 0,
    "summary": "",
    "tags": [],
    "hasDiagrams": false,
    "prev": "ai-tooling-crash-course-for-developers/topics/skill-libraries-and-marketplaces",
    "next": "ai-tooling-crash-course-for-developers/topics/subagents-and-delegation"
  },
  {
    "path": "ai-tooling-crash-course-for-developers/topics/subagents-and-delegation",
    "title": "Subagents And Delegation",
    "order": 0,
    "summary": "",
    "tags": [],
    "hasDiagrams": false,
    "prev": "ai-tooling-crash-course-for-developers/topics/skill-scanning-and-verification",
    "next": null
  }
];

export const LIBRARY_DOC_PATHS: readonly string[] = ["ai-tooling-crash-course-for-developers/_ai-tooling-recommendations","ai-tooling-crash-course-for-developers/_inspiration-and-staying-current","ai-tooling-crash-course-for-developers/0-how-llms-actually-work-under-the-hood","ai-tooling-crash-course-for-developers/README","ai-tooling-crash-course-for-developers/topics/agent-sandboxing","ai-tooling-crash-course-for-developers/topics/base-instruction-files","ai-tooling-crash-course-for-developers/topics/dev-scoped-second-brain-rag","ai-tooling-crash-course-for-developers/topics/graph-engineering-multi-agent-coordination","ai-tooling-crash-course-for-developers/topics/harness-engineering-vocabulary","ai-tooling-crash-course-for-developers/topics/local-model-hardware-fit","ai-tooling-crash-course-for-developers/topics/loop-engineering-agent-loops","ai-tooling-crash-course-for-developers/topics/mcp-model-context-protocol","ai-tooling-crash-course-for-developers/topics/memory-and-progress-ledgers","ai-tooling-crash-course-for-developers/topics/personal-harness-architecture","ai-tooling-crash-course-for-developers/topics/planning-before-implementation","ai-tooling-crash-course-for-developers/topics/prompt-engineering","ai-tooling-crash-course-for-developers/topics/protocol-landscape-acp-a2a","ai-tooling-crash-course-for-developers/topics/review-and-verification-tooling","ai-tooling-crash-course-for-developers/topics/security-and-supply-chain","ai-tooling-crash-course-for-developers/topics/session-and-token-economics","ai-tooling-crash-course-for-developers/topics/skill-libraries-and-marketplaces","ai-tooling-crash-course-for-developers/topics/skill-scanning-and-verification","ai-tooling-crash-course-for-developers/topics/subagents-and-delegation"];

export const LIBRARY_FOLDER_PATHS: readonly string[] = ["ai-tooling-crash-course-for-developers","ai-tooling-crash-course-for-developers/topics"];

export const LIBRARY_DOC_REDIRECTS: readonly LibraryDocRedirect[] = [
  {
    "from": "ai-tooling-crash-course-for-developers/agent-sandboxing",
    "to": "ai-tooling-crash-course-for-developers/topics/agent-sandboxing"
  },
  {
    "from": "ai-tooling-crash-course-for-developers/base-instruction-files",
    "to": "ai-tooling-crash-course-for-developers/topics/base-instruction-files"
  },
  {
    "from": "ai-tooling-crash-course-for-developers/dev-scoped-second-brain-rag",
    "to": "ai-tooling-crash-course-for-developers/topics/dev-scoped-second-brain-rag"
  },
  {
    "from": "ai-tooling-crash-course-for-developers/graph-engineering-multi-agent-coordination",
    "to": "ai-tooling-crash-course-for-developers/topics/graph-engineering-multi-agent-coordination"
  },
  {
    "from": "ai-tooling-crash-course-for-developers/harness-engineering-vocabulary",
    "to": "ai-tooling-crash-course-for-developers/topics/harness-engineering-vocabulary"
  },
  {
    "from": "ai-tooling-crash-course-for-developers/local-model-hardware-fit",
    "to": "ai-tooling-crash-course-for-developers/topics/local-model-hardware-fit"
  },
  {
    "from": "ai-tooling-crash-course-for-developers/loop-engineering-agent-loops",
    "to": "ai-tooling-crash-course-for-developers/topics/loop-engineering-agent-loops"
  },
  {
    "from": "ai-tooling-crash-course-for-developers/mcp-model-context-protocol",
    "to": "ai-tooling-crash-course-for-developers/topics/mcp-model-context-protocol"
  },
  {
    "from": "ai-tooling-crash-course-for-developers/memory-and-progress-ledgers",
    "to": "ai-tooling-crash-course-for-developers/topics/memory-and-progress-ledgers"
  },
  {
    "from": "ai-tooling-crash-course-for-developers/personal-harness-architecture",
    "to": "ai-tooling-crash-course-for-developers/topics/personal-harness-architecture"
  },
  {
    "from": "ai-tooling-crash-course-for-developers/planning-before-implementation",
    "to": "ai-tooling-crash-course-for-developers/topics/planning-before-implementation"
  },
  {
    "from": "ai-tooling-crash-course-for-developers/prompt-engineering",
    "to": "ai-tooling-crash-course-for-developers/topics/prompt-engineering"
  },
  {
    "from": "ai-tooling-crash-course-for-developers/protocol-landscape-acp-a2a",
    "to": "ai-tooling-crash-course-for-developers/topics/protocol-landscape-acp-a2a"
  },
  {
    "from": "ai-tooling-crash-course-for-developers/review-and-verification-tooling",
    "to": "ai-tooling-crash-course-for-developers/topics/review-and-verification-tooling"
  },
  {
    "from": "ai-tooling-crash-course-for-developers/security-and-supply-chain",
    "to": "ai-tooling-crash-course-for-developers/topics/security-and-supply-chain"
  },
  {
    "from": "ai-tooling-crash-course-for-developers/session-and-token-economics",
    "to": "ai-tooling-crash-course-for-developers/topics/session-and-token-economics"
  },
  {
    "from": "ai-tooling-crash-course-for-developers/skill-libraries-and-marketplaces",
    "to": "ai-tooling-crash-course-for-developers/topics/skill-libraries-and-marketplaces"
  },
  {
    "from": "ai-tooling-crash-course-for-developers/skill-scanning-and-verification",
    "to": "ai-tooling-crash-course-for-developers/topics/skill-scanning-and-verification"
  },
  {
    "from": "ai-tooling-crash-course-for-developers/subagents-and-delegation",
    "to": "ai-tooling-crash-course-for-developers/topics/subagents-and-delegation"
  },
  {
    "from": "learn",
    "to": "ai-tooling-crash-course-for-developers"
  },
  {
    "from": "learn/topics",
    "to": "ai-tooling-crash-course-for-developers/topics"
  },
  {
    "from": "learn/_ai-tooling-recommendations",
    "to": "ai-tooling-crash-course-for-developers/_ai-tooling-recommendations"
  },
  {
    "from": "learn/_inspiration-and-staying-current",
    "to": "ai-tooling-crash-course-for-developers/_inspiration-and-staying-current"
  },
  {
    "from": "learn/0-how-llms-actually-work-under-the-hood",
    "to": "ai-tooling-crash-course-for-developers/0-how-llms-actually-work-under-the-hood"
  },
  {
    "from": "learn/README",
    "to": "ai-tooling-crash-course-for-developers/README"
  },
  {
    "from": "learn/topics/agent-sandboxing",
    "to": "ai-tooling-crash-course-for-developers/topics/agent-sandboxing"
  },
  {
    "from": "learn/topics/base-instruction-files",
    "to": "ai-tooling-crash-course-for-developers/topics/base-instruction-files"
  },
  {
    "from": "learn/topics/dev-scoped-second-brain-rag",
    "to": "ai-tooling-crash-course-for-developers/topics/dev-scoped-second-brain-rag"
  },
  {
    "from": "learn/topics/graph-engineering-multi-agent-coordination",
    "to": "ai-tooling-crash-course-for-developers/topics/graph-engineering-multi-agent-coordination"
  },
  {
    "from": "learn/topics/harness-engineering-vocabulary",
    "to": "ai-tooling-crash-course-for-developers/topics/harness-engineering-vocabulary"
  },
  {
    "from": "learn/topics/local-model-hardware-fit",
    "to": "ai-tooling-crash-course-for-developers/topics/local-model-hardware-fit"
  },
  {
    "from": "learn/topics/loop-engineering-agent-loops",
    "to": "ai-tooling-crash-course-for-developers/topics/loop-engineering-agent-loops"
  },
  {
    "from": "learn/topics/mcp-model-context-protocol",
    "to": "ai-tooling-crash-course-for-developers/topics/mcp-model-context-protocol"
  },
  {
    "from": "learn/topics/memory-and-progress-ledgers",
    "to": "ai-tooling-crash-course-for-developers/topics/memory-and-progress-ledgers"
  },
  {
    "from": "learn/topics/personal-harness-architecture",
    "to": "ai-tooling-crash-course-for-developers/topics/personal-harness-architecture"
  },
  {
    "from": "learn/topics/planning-before-implementation",
    "to": "ai-tooling-crash-course-for-developers/topics/planning-before-implementation"
  },
  {
    "from": "learn/topics/prompt-engineering",
    "to": "ai-tooling-crash-course-for-developers/topics/prompt-engineering"
  },
  {
    "from": "learn/topics/protocol-landscape-acp-a2a",
    "to": "ai-tooling-crash-course-for-developers/topics/protocol-landscape-acp-a2a"
  },
  {
    "from": "learn/topics/review-and-verification-tooling",
    "to": "ai-tooling-crash-course-for-developers/topics/review-and-verification-tooling"
  },
  {
    "from": "learn/topics/security-and-supply-chain",
    "to": "ai-tooling-crash-course-for-developers/topics/security-and-supply-chain"
  },
  {
    "from": "learn/topics/session-and-token-economics",
    "to": "ai-tooling-crash-course-for-developers/topics/session-and-token-economics"
  },
  {
    "from": "learn/topics/skill-libraries-and-marketplaces",
    "to": "ai-tooling-crash-course-for-developers/topics/skill-libraries-and-marketplaces"
  },
  {
    "from": "learn/topics/skill-scanning-and-verification",
    "to": "ai-tooling-crash-course-for-developers/topics/skill-scanning-and-verification"
  },
  {
    "from": "learn/topics/subagents-and-delegation",
    "to": "ai-tooling-crash-course-for-developers/topics/subagents-and-delegation"
  },
  {
    "from": "ai-tooling-crash-course-for-developers/topic-index",
    "to": "ai-tooling-crash-course-for-developers/README"
  },
  {
    "from": "learn/topic-index",
    "to": "ai-tooling-crash-course-for-developers/README"
  }
];

export const LIBRARY_SLUG_PATHS: Readonly<Record<string, string>> = {
  "_ai-tooling-recommendations": "ai-tooling-crash-course-for-developers/_ai-tooling-recommendations",
  "_inspiration-and-staying-current": "ai-tooling-crash-course-for-developers/_inspiration-and-staying-current",
  "0-how-llms-actually-work-under-the-hood": "ai-tooling-crash-course-for-developers/0-how-llms-actually-work-under-the-hood",
  "README": "ai-tooling-crash-course-for-developers/README",
  "agent-sandboxing": "ai-tooling-crash-course-for-developers/topics/agent-sandboxing",
  "base-instruction-files": "ai-tooling-crash-course-for-developers/topics/base-instruction-files",
  "dev-scoped-second-brain-rag": "ai-tooling-crash-course-for-developers/topics/dev-scoped-second-brain-rag",
  "graph-engineering-multi-agent-coordination": "ai-tooling-crash-course-for-developers/topics/graph-engineering-multi-agent-coordination",
  "harness-engineering-vocabulary": "ai-tooling-crash-course-for-developers/topics/harness-engineering-vocabulary",
  "local-model-hardware-fit": "ai-tooling-crash-course-for-developers/topics/local-model-hardware-fit",
  "loop-engineering-agent-loops": "ai-tooling-crash-course-for-developers/topics/loop-engineering-agent-loops",
  "mcp-model-context-protocol": "ai-tooling-crash-course-for-developers/topics/mcp-model-context-protocol",
  "memory-and-progress-ledgers": "ai-tooling-crash-course-for-developers/topics/memory-and-progress-ledgers",
  "personal-harness-architecture": "ai-tooling-crash-course-for-developers/topics/personal-harness-architecture",
  "planning-before-implementation": "ai-tooling-crash-course-for-developers/topics/planning-before-implementation",
  "prompt-engineering": "ai-tooling-crash-course-for-developers/topics/prompt-engineering",
  "protocol-landscape-acp-a2a": "ai-tooling-crash-course-for-developers/topics/protocol-landscape-acp-a2a",
  "review-and-verification-tooling": "ai-tooling-crash-course-for-developers/topics/review-and-verification-tooling",
  "security-and-supply-chain": "ai-tooling-crash-course-for-developers/topics/security-and-supply-chain",
  "session-and-token-economics": "ai-tooling-crash-course-for-developers/topics/session-and-token-economics",
  "skill-libraries-and-marketplaces": "ai-tooling-crash-course-for-developers/topics/skill-libraries-and-marketplaces",
  "skill-scanning-and-verification": "ai-tooling-crash-course-for-developers/topics/skill-scanning-and-verification",
  "subagents-and-delegation": "ai-tooling-crash-course-for-developers/topics/subagents-and-delegation"
};

export const LIBRARY_DOC_LOADERS: Record<string, () => Promise<{ HTML: string }>> = {
  'ai-tooling-crash-course-for-developers/_ai-tooling-recommendations': () => import('./docs/ai-tooling-crash-course-for-developers___ai-tooling-recommendations.generated'),
  'ai-tooling-crash-course-for-developers/_inspiration-and-staying-current': () => import('./docs/ai-tooling-crash-course-for-developers___inspiration-and-staying-current.generated'),
  'ai-tooling-crash-course-for-developers/0-how-llms-actually-work-under-the-hood': () => import('./docs/ai-tooling-crash-course-for-developers__0-how-llms-actually-work-under-the-hood.generated'),
  'ai-tooling-crash-course-for-developers/README': () => import('./docs/ai-tooling-crash-course-for-developers__README.generated'),
  'ai-tooling-crash-course-for-developers/topics/agent-sandboxing': () => import('./docs/ai-tooling-crash-course-for-developers__topics__agent-sandboxing.generated'),
  'ai-tooling-crash-course-for-developers/topics/base-instruction-files': () => import('./docs/ai-tooling-crash-course-for-developers__topics__base-instruction-files.generated'),
  'ai-tooling-crash-course-for-developers/topics/dev-scoped-second-brain-rag': () => import('./docs/ai-tooling-crash-course-for-developers__topics__dev-scoped-second-brain-rag.generated'),
  'ai-tooling-crash-course-for-developers/topics/graph-engineering-multi-agent-coordination': () => import('./docs/ai-tooling-crash-course-for-developers__topics__graph-engineering-multi-agent-coordination.generated'),
  'ai-tooling-crash-course-for-developers/topics/harness-engineering-vocabulary': () => import('./docs/ai-tooling-crash-course-for-developers__topics__harness-engineering-vocabulary.generated'),
  'ai-tooling-crash-course-for-developers/topics/local-model-hardware-fit': () => import('./docs/ai-tooling-crash-course-for-developers__topics__local-model-hardware-fit.generated'),
  'ai-tooling-crash-course-for-developers/topics/loop-engineering-agent-loops': () => import('./docs/ai-tooling-crash-course-for-developers__topics__loop-engineering-agent-loops.generated'),
  'ai-tooling-crash-course-for-developers/topics/mcp-model-context-protocol': () => import('./docs/ai-tooling-crash-course-for-developers__topics__mcp-model-context-protocol.generated'),
  'ai-tooling-crash-course-for-developers/topics/memory-and-progress-ledgers': () => import('./docs/ai-tooling-crash-course-for-developers__topics__memory-and-progress-ledgers.generated'),
  'ai-tooling-crash-course-for-developers/topics/personal-harness-architecture': () => import('./docs/ai-tooling-crash-course-for-developers__topics__personal-harness-architecture.generated'),
  'ai-tooling-crash-course-for-developers/topics/planning-before-implementation': () => import('./docs/ai-tooling-crash-course-for-developers__topics__planning-before-implementation.generated'),
  'ai-tooling-crash-course-for-developers/topics/prompt-engineering': () => import('./docs/ai-tooling-crash-course-for-developers__topics__prompt-engineering.generated'),
  'ai-tooling-crash-course-for-developers/topics/protocol-landscape-acp-a2a': () => import('./docs/ai-tooling-crash-course-for-developers__topics__protocol-landscape-acp-a2a.generated'),
  'ai-tooling-crash-course-for-developers/topics/review-and-verification-tooling': () => import('./docs/ai-tooling-crash-course-for-developers__topics__review-and-verification-tooling.generated'),
  'ai-tooling-crash-course-for-developers/topics/security-and-supply-chain': () => import('./docs/ai-tooling-crash-course-for-developers__topics__security-and-supply-chain.generated'),
  'ai-tooling-crash-course-for-developers/topics/session-and-token-economics': () => import('./docs/ai-tooling-crash-course-for-developers__topics__session-and-token-economics.generated'),
  'ai-tooling-crash-course-for-developers/topics/skill-libraries-and-marketplaces': () => import('./docs/ai-tooling-crash-course-for-developers__topics__skill-libraries-and-marketplaces.generated'),
  'ai-tooling-crash-course-for-developers/topics/skill-scanning-and-verification': () => import('./docs/ai-tooling-crash-course-for-developers__topics__skill-scanning-and-verification.generated'),
  'ai-tooling-crash-course-for-developers/topics/subagents-and-delegation': () => import('./docs/ai-tooling-crash-course-for-developers__topics__subagents-and-delegation.generated'),
};
