// Writes src/app/primeui-license.ts from the environment.
//
// The PrimeUI licence token is a credential and is never committed. It is read
// from the PRIMEUI_LICENSE environment variable, falling back to the
// gitignored .primeui-license file, and written to a generated module that
// app.config.ts imports and hands to providePrimeNG.
//
// With no token configured the generated module exports an empty string. That
// is a valid state: PrimeNG reports the missing licence itself (a console
// warning and an on-page banner), so a fresh clone builds and runs unchanged.
//
// Idempotent, and safe to run on every build.

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const tokenFile = join(root, '.primeui-license');
const outFile = join(root, 'src', 'app', 'primeui-license.ts');

const fromEnv = process.env.PRIMEUI_LICENSE?.trim() ?? '';
const fromFile = existsSync(tokenFile) ? readFileSync(tokenFile, 'utf8').trim() : '';
const token = fromEnv || fromFile;

const header = [
  '// Generated by scripts/primeui-license.mjs. Do not edit, do not commit.',
  '// The token lives in .primeui-license (gitignored) or PRIMEUI_LICENSE.',
  '',
].join('\n');

writeFileSync(outFile, `${header}export const PRIMEUI_LICENSE = ${JSON.stringify(token)};\n`);

console.log(
  `primeui-license: ${token ? 'token configured' : 'no token - PrimeNG will report the missing licence'}`,
);
