import type { MermaidConfig } from 'mermaid';

/** Diagrams sit on the paper sheet, so they use the sheet ink and a single blue edge. */
export const markdownMermaidConfig = {
  startOnLoad: false,
  securityLevel: 'strict',
  theme: 'base',
  fontFamily: "'Inter', -apple-system, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
  flowchart: {
    htmlLabels: true,
    curve: 'basis',
    padding: 14,
    nodeSpacing: 40,
    rankSpacing: 40,
    useMaxWidth: true,
  },
  themeVariables: {
    darkMode: false,
    background: 'transparent',
    fontFamily: "'Inter', -apple-system, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
    fontSize: '15px',
    textColor: '#111827',
    primaryColor: '#ffffff',
    primaryTextColor: '#111827',
    primaryBorderColor: '#0e8c99',
    secondaryColor: '#f5f5f5',
    secondaryTextColor: '#111827',
    secondaryBorderColor: '#0e8c99',
    tertiaryColor: '#f5f5f5',
    tertiaryTextColor: '#111827',
    tertiaryBorderColor: '#9ca3af',
    lineColor: '#0e8c99',
    mainBkg: '#ffffff',
    nodeBorder: '#0e8c99',
    nodeTextColor: '#111827',
    clusterBkg: '#f5f5f5',
    clusterBorder: '#0e8c99',
    titleColor: '#111827',
    edgeLabelBackground: '#fafafa',
    defaultLinkColor: '#0e8c99',
    actorBkg: '#ffffff',
    actorBorder: '#0e8c99',
    actorTextColor: '#111827',
    actorLineColor: '#0e8c99',
    signalColor: '#111827',
    signalTextColor: '#111827',
    labelBoxBkgColor: '#f5f5f5',
    labelBoxBorderColor: '#0e8c99',
    labelTextColor: '#111827',
    noteBkgColor: '#f5f5f5',
    noteTextColor: '#111827',
    noteBorderColor: '#0e8c99',
  },
} satisfies MermaidConfig;
